#!/bin/bash

touch .vimspector.json
exec 1>.vimspector.json

echo -n '{
  "configurations": {
    "Launch": {
      "adapter": "vscode-cpptools",
      "configuration": {
        "request": "launch",
        "program": " '
echo -n "$(pwd)/bin/$1 "
echo '",'
echo -n '"cwd": " '
echo -n "$(pwd)/debug "
echo '",'
echo -n '"externalConsole": true,
        "MIMode": "gdb"
      }
    },
    "Attach": {
      "adapter": "vscode-cpptools",
      "configuration": {
        "request": "attach",
        "program": " '
echo -n "$(pwd)/bin/$1 "
echo  '",'
echo  '     "MIMode": "gdb"
      }
    }
    
  }
}'
